---
version: '3.4'

x-common:
  &common
  user: "${AIRFLOW_UID}:0"
  env_file: 
    - .env
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./sample_data:/tmp/sample_data
    - ./oly_dbt:/opt/dbt/oly_dbt
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - /var/run/docker.sock:/var/run/docker.sock

x-depends-on:
  &depends-on
  depends_on:
    postgres:
      condition: service_healthy
    airflow-init:
      condition: service_completed_successfully

services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - ./sample_data:/tmp/sample_data

  scheduler:
    <<: *common
    <<: *depends-on
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    #command: scheduler
    restart: on-failure
    ports:
      - "8793:8793"
      - "8282:8080"

  webserver:
    <<: *common
    <<: *depends-on
    image: apache/airflow:2.3.0
    container_name: airflow-webserver
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
  
  airflow-init:
    <<: *common
    image: apache/airflow:2.3.0
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version